version: "2"
run:
  concurrency: 2
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - godot
    - gomodguard
    - gosmopolitan
    - grouper
    - ireturn
    - loggercheck
    - nlreturn
    - paralleltest
    - perfsprint
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - tagalign
    - testifylint
    - unparam
    - testpackage
    - varnamelen
    - whitespace
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
