// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ThreadCreator is an autogenerated mock type for the ThreadCreator type
type ThreadCreator struct {
	mock.Mock
}

// CreateThread provides a mock function with given fields: ctx, channelID, name, message
func (_m *ThreadCreator) CreateThread(ctx context.Context, channelID string, name string, message string) error {
	ret := _m.Called(ctx, channelID, name, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, channelID, name, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewThreadCreator creates a new instance of ThreadCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThreadCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThreadCreator {
	mock := &ThreadCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
