// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/xgnid-tw/gx5/domain"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetOthersUnpaidAmount provides a mock function with given fields: ctx, buyerName, currency
func (_m *UserRepository) GetOthersUnpaidAmount(ctx context.Context, buyerName string, currency domain.Currency) (float64, error) {
	ret := _m.Called(ctx, buyerName, currency)

	if len(ret) == 0 {
		panic("no return value specified for GetOthersUnpaidAmount")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Currency) (float64, error)); ok {
		return rf(ctx, buyerName, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Currency) float64); ok {
		r0 = rf(ctx, buyerName, currency)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Currency) error); ok {
		r1 = rf(ctx, buyerName, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnpaidAmount provides a mock function with given fields: ctx, userDatabaseID, currency
func (_m *UserRepository) GetUnpaidAmount(ctx context.Context, userDatabaseID string, currency domain.Currency) (float64, error) {
	ret := _m.Called(ctx, userDatabaseID, currency)

	if len(ret) == 0 {
		panic("no return value specified for GetUnpaidAmount")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Currency) (float64, error)); ok {
		return rf(ctx, userDatabaseID, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Currency) float64); ok {
		r0 = rf(ctx, userDatabaseID, currency)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Currency) error); ok {
		r1 = rf(ctx, userDatabaseID, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx
func (_m *UserRepository) GetUsers(ctx context.Context) ([]*domain.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
