// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/xgnid-tw/gx5/domain"

	port "github.com/xgnid-tw/gx5/port"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUnpaidSummary provides a mock function with given fields: ctx, userDatabaseID, currency
func (_m *UserRepository) GetUnpaidSummary(ctx context.Context, userDatabaseID string, currency domain.Currency) (*port.UnpaidSummary, error) {
	ret := _m.Called(ctx, userDatabaseID, currency)

	if len(ret) == 0 {
		panic("no return value specified for GetUnpaidSummary")
	}

	var r0 *port.UnpaidSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Currency) (*port.UnpaidSummary, error)); ok {
		return rf(ctx, userDatabaseID, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Currency) *port.UnpaidSummary); ok {
		r0 = rf(ctx, userDatabaseID, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.UnpaidSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Currency) error); ok {
		r1 = rf(ctx, userDatabaseID, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByDiscordID provides a mock function with given fields: ctx, discordID
func (_m *UserRepository) GetUserByDiscordID(ctx context.Context, discordID string) (*domain.User, error) {
	ret := _m.Called(ctx, discordID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByDiscordID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, discordID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, discordID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, discordID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx
func (_m *UserRepository) GetUsers(ctx context.Context) ([]*domain.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
